spring.application.name=myfin
# Данни за връзка
spring.datasource.url=jdbc:postgresql://localhost:5432/transactions_central
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройка за генериране на таблици (DDL)
spring.jpa.hibernate.ddl-auto=update

# По желание: показва SQL заявките в конзолата, за да видите какво прави Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.name=My financial application
app.seeding=true